//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Common {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalFormat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalFormat() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.Common.GlobalFormat", typeof(GlobalFormat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0:0,0.00}.
        /// </summary>
        internal static string Decimal2 {
            get {
                return ResourceManager.GetString("Decimal2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0:0,0.000}.
        /// </summary>
        internal static string Decimal3 {
            get {
                return ResourceManager.GetString("Decimal3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0:#,##0.00000.
        /// </summary>
        internal static string Decimal5 {
            get {
                return ResourceManager.GetString("Decimal5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy HH:mm:ss.
        /// </summary>
        internal static string FormatoFecha {
            get {
                return ResourceManager.GetString("FormatoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy.
        /// </summary>
        internal static string FormatoFechaCorta {
            get {
                return ResourceManager.GetString("FormatoFechaCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hh:mm tt.
        /// </summary>
        internal static string FormatoHora {
            get {
                return ResourceManager.GetString("FormatoHora", resourceCulture);
            }
        }
    }
}
