// Generated by CoffeeScript 1.12.3
(function() {
  this.app = {
    toggleSidebar: function() {
      return $("#inner-sidebar .header a").on("click", function(e) {
        e.preventDefault();
        $("sidebar#sidebar").toggleClass("active");
        return $(window).resize(function() {
          if ($(".container").width >= 750) {
            if (!$("sidebar#sidebar").hasClass(active)) {
              return $("sidebar#sidebar").addClass("active");
            }
          }
        });
      });
    }
  };

}).call(this);
