//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiado
    {
        public int ID { get; set; }
        public int SolicitudID { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public Nullable<int> UsersID { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> FlagPrincipal { get; set; }
        public string NumeroDocumento { get; set; }
        public string CodigoCentroCosto { get; set; }
        public string Apellidos { get; set; }
    
        public virtual CentroCosto CentroCosto { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
