//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroCosto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CentroCosto()
        {
            this.Beneficiado = new HashSet<Beneficiado>();
            this.Usuario1 = new HashSet<Usuario>();
            this.UsuarioCentroCosto = new HashSet<UsuarioCentroCosto>();
        }
    
        public string Codigo { get; set; }
        public Nullable<System.DateTime> ValidoHasta { get; set; }
        public Nullable<System.DateTime> ValidoDesde { get; set; }
        public string Soc { get; set; }
        public string Denominacion { get; set; }
        public string Descripcion { get; set; }
        public string TextoBreve { get; set; }
        public Nullable<bool> FlagCosto { get; set; }
        public Nullable<bool> FlagGasto { get; set; }
        public Nullable<int> IdResponsable { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiado> Beneficiado { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioCentroCosto> UsuarioCentroCosto { get; set; }
    }
}
