//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredencialesProveedorTaxi
    {
        public int ID { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string UserName { get; set; }
        public string Contraseña { get; set; }
        public string GrantType { get; set; }
        public string KeyApi { get; set; }
    
        public virtual ProveedorTaxi ProveedorTaxi { get; set; }
    }
}
