//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GastoAdicional
    {
        public int ID { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> TiempoMinuto { get; set; }
    
        public virtual Concepto Concepto { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
