//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liquidacion()
        {
            this.LiquidacionDetalle = new HashSet<LiquidacionDetalle>();
        }
    
        public int ID { get; set; }
        public string Codigo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ProveedorTaxiID { get; set; }
        public string CodigoSociedad { get; set; }
        public decimal Total { get; set; }
        public int Estado { get; set; }
        public string UsuarioRegistro { get; set; }
        public string UsuarioCancelo { get; set; }
        public string UserNameCancelo { get; set; }
        public string UsuarioLiquido { get; set; }
        public Nullable<System.DateTime> FechaLiquidacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public string UserNameRegistro { get; set; }
        public string UserNameLiquido { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public int SociedadID { get; set; }
        public string Observacion { get; set; }
        public string Factura { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public string AsientoContable { get; set; }
        public string Ejercicio { get; set; }
        public Nullable<System.DateTime> DiaRegistro { get; set; }
        public string UsuarioRegistroSAP { get; set; }
        public string HoraRegistro { get; set; }
        public string Mensaje { get; set; }
        public string FacturaProvision { get; set; }
        public Nullable<System.DateTime> Fecha_Contable { get; set; }
        public string Moneda { get; set; }
        public string Flag_Imp { get; set; }
        public string Indicadore_Igv { get; set; }
        public string Lugar_Comer { get; set; }
        public string Indicador_Cme { get; set; }
        public string Cta_Mayor { get; set; }
        public string Indicador_D_H { get; set; }
        public string NombreFile { get; set; }
        public string RutaCompletaFile { get; set; }
    
        public virtual LiquidacionEstado LiquidacionEstado { get; set; }
        public virtual ProveedorTaxi ProveedorTaxi { get; set; }
        public virtual Sociedad Sociedad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidacionDetalle> LiquidacionDetalle { get; set; }
    }
}
