//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiquidacionDetalle
    {
        public int LiquidacionDetalleID { get; set; }
        public int LiquidacionID { get; set; }
        public int SolicitudID { get; set; }
        public string OrdenServicio { get; set; }
        public string CentroCostoAfecto { get; set; }
        public Nullable<decimal> PrecioTarifa { get; set; }
        public Nullable<decimal> PrecioEspera { get; set; }
        public Nullable<decimal> PrecioDesvioRuta { get; set; }
        public Nullable<decimal> PrecioPeaje { get; set; }
        public Nullable<decimal> PrecioEstacionamiento { get; set; }
        public Nullable<decimal> TotalGeneral { get; set; }
        public Nullable<decimal> PrecioDesplazamiento { get; set; }
    
        public virtual Liquidacion Liquidacion { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
