//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorTaxi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProveedorTaxi()
        {
            this.Automovil = new HashSet<Automovil>();
            this.Conductor = new HashSet<Conductor>();
            this.CredencialesProveedorTaxi = new HashSet<CredencialesProveedorTaxi>();
            this.Destino = new HashSet<Destino>();
            this.Liquidacion = new HashSet<Liquidacion>();
            this.ServicioProveedorTaxi = new HashSet<ServicioProveedorTaxi>();
            this.Solicitud = new HashSet<Solicitud>();
            this.SolicitudProveedorTaxi = new HashSet<SolicitudProveedorTaxi>();
        }
    
        public int ID { get; set; }
        public string RazonSocial { get; set; }
        public string RUC { get; set; }
        public Nullable<decimal> TiempoReserva { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Direccion { get; set; }
        public string CodigoSAP { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdIndicadorIGVFactura { get; set; }
        public Nullable<int> IdIndicadorIGVProvision { get; set; }
        public Nullable<decimal> TiempoEspera { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> FlagSeleccionado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Automovil> Automovil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conductor> Conductor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CredencialesProveedorTaxi> CredencialesProveedorTaxi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Destino> Destino { get; set; }
        public virtual EstadoProveedor EstadoProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidacion> Liquidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicioProveedorTaxi> ServicioProveedorTaxi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudProveedorTaxi> SolicitudProveedorTaxi { get; set; }
    }
}
