//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioProveedorTaxi
    {
        public int ID { get; set; }
        public Nullable<int> IdMetodoProveedorTaxi { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string URL { get; set; }
        public string Metodo { get; set; }
    
        public virtual MetodoProveedorTaxi MetodoProveedorTaxi { get; set; }
        public virtual ProveedorTaxi ProveedorTaxi { get; set; }
    }
}
