//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudProveedorTaxi
    {
        public int ID { get; set; }
        public int SolicitudID { get; set; }
        public int ProveedorTaxiID { get; set; }
        public Nullable<decimal> PrecioServicio { get; set; }
        public string Seleccionado { get; set; }
    
        public virtual ProveedorTaxi ProveedorTaxi { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
