//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudDetalle
    {
        public int ID { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdConductor { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public string NombreConductor { get; set; }
        public string DocumentoConductor { get; set; }
        public string ModeloAutomovil { get; set; }
        public string PlacaAutomovil { get; set; }
        public Nullable<int> IdSituacion { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual EstadoProveedor EstadoProveedor { get; set; }
        public virtual SituacionServicio SituacionServicio { get; set; }
        public virtual Solicitud Solicitud { get; set; }
    }
}
