//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitud()
        {
            this.Beneficiado = new HashSet<Beneficiado>();
            this.GastoAdicional = new HashSet<GastoAdicional>();
            this.LiquidacionDetalle = new HashSet<LiquidacionDetalle>();
            this.SolicitudDetalle = new HashSet<SolicitudDetalle>();
            this.Tracking = new HashSet<Tracking>();
            this.SolicitudProveedorTaxi = new HashSet<SolicitudProveedorTaxi>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IdServicioProveedor { get; set; }
        public Nullable<int> IdTipoServicio { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public Nullable<int> IdProveedorTaxi { get; set; }
        public Nullable<int> IdEstadoServicioProveedor { get; set; }
        public string TipoServicio { get; set; }
        public Nullable<System.DateTime> FechaServicio { get; set; }
        public Nullable<int> HoraServicioEnMinutos { get; set; }
        public string CentroCostoAfectoCodigoSap { get; set; }
        public string CentroCostoAfectoDescripcion { get; set; }
        public string NroOrdenServicio { get; set; }
        public Nullable<int> CantidadHoras { get; set; }
        public string OrigenDireccion { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string TipoDestino { get; set; }
        public string MotivoCancelacion { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> MotivoCreacionSolicitudID { get; set; }
        public string MotivoRechazo { get; set; }
        public string Observaciones { get; set; }
        public Nullable<decimal> TotalServicio { get; set; }
        public string TelefonoPrincipal { get; set; }
        public Nullable<decimal> DistanciaKilometro { get; set; }
        public Nullable<decimal> TotalGasto { get; set; }
        public Nullable<decimal> TotalGeneral { get; set; }
        public Nullable<int> SituacionServicio { get; set; }
        public string Sociedad { get; set; }
        public Nullable<bool> Liquidado { get; set; }
        public Nullable<int> IdConductor { get; set; }
        public Nullable<int> IdAutomovil { get; set; }
        public Nullable<int> IdTipoDestino { get; set; }
        public Nullable<int> IdMotivoCreacionSolicitud { get; set; }
        public Nullable<int> IdSituacionServicio { get; set; }
        public Nullable<int> IdSociedad { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string UsuarioAprobo { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public string UserNameRegistro { get; set; }
        public string UserNameAprobo { get; set; }
        public string ComentarioCalificacion { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<int> IdUsuarioAprobador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiado> Beneficiado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GastoAdicional> GastoAdicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LiquidacionDetalle> LiquidacionDetalle { get; set; }
        public virtual MotivoCreacionSolicitud MotivoCreacionSolicitud { get; set; }
        public virtual MotivoCreacionSolicitud MotivoCreacionSolicitud1 { get; set; }
        public virtual ProveedorTaxi ProveedorTaxi { get; set; }
        public virtual SituacionServicio SituacionServicio1 { get; set; }
        public virtual SituacionServicio SituacionServicio2 { get; set; }
        public virtual Sociedad Sociedad1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudDetalle> SolicitudDetalle { get; set; }
        public virtual TipoServicio TipoServicio1 { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        public virtual TipoDestino TipoDestino1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking> Tracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudProveedorTaxi> SolicitudProveedorTaxi { get; set; }
    }
}
