//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int ID { get; set; }
        public decimal Latitud { get; set; }
        public decimal Longitud { get; set; }
        public Nullable<System.DateTime> FechaTracking { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
    
        public virtual Solicitud Solicitud { get; set; }
    }
}
